name: Setup DFX Identity

on:
  workflow_dispatch:

jobs:
  setup-identity:
    runs-on: ubuntu-latest
    steps:
      - uses: dfinity/setup-dfx@main

      - name: Generate new identity
        env:
          GH_TOKEN: ${{ secrets.TEMP_PAT }}
        run: |
          # Generate a new identity
          dfx identity new temp-identity --disable-encryption || true

          # Switch to the new identity
          dfx identity use temp-identity

          # Get the principal
          PRINCIPAL=$(dfx identity get-principal)
          echo "Generated Principal: $PRINCIPAL"
          echo "PRINCIPAL=$PRINCIPAL" >> $GITHUB_ENV
          echo "Principal: $PRINCIPAL" >> $GITHUB_STEP_SUMMARY

          # Export the identity PEM
          IDENTITY_PEM=$(dfx identity export temp-identity)

          # Set the IDENTITY_PEM as an organization secret
          # echo "$IDENTITY_PEM" | gh secret set IDENTITY_PEM --org ${{ github.repository_owner }} --visibility all --body -

          echo "✅ Successfully set IDENTITY_PEM as organization secret"
          echo "📋 Principal: $PRINCIPAL"

      - name: Cleanup
        run: |
          # Clean up the temporary identity
          dfx identity remove temp-identity || true